---
version: '2'
services:
###
  registry:
    image: registry
    ports:
      - "5000:5000"
    volumes:
      - registry_data:/var/lib/registry
    environment:
      SETTINGS_FLAVOR: local 
      STORAGE_PATH: /var/lib/docker/registry
      SEARCH_BACKEND: sqlalchemy
      CACHE_REDIS_HOST: cache 
      CACHE_REDIS_PORT: 6379
      CACHE_LRU_REDIS_HOST: cache 
      CACHE_LRU_REDIS_PORT: 6379
    depends_on:
      - cache
###
  cache: 
    image: redis 
###
  
  frontend:
    image: konradkleine/docker-registry-frontend
    ports:
      - "8081:80"
    environment:
      ENV_DOCKER_REGISTRY_HOST: registry
      ENV_DOCKER_REGISTRY_PORT: 5000
    depends_on:
      - registry

###
volumes:
  registry_data: {}
