---
version: '2'
services:
###
  registry:
    image: registry:2
    ports:
      - "5000:5000"
    volumes:
      - registry_data:/var/lib/registry
      - ./certs:/certs
    environment:
      STORAGE_PATH: /var/lib/docker/registry
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      REGISTRY_HTTP_TLS_KEY: /certs/domain.key
      LOGLEVEL: INFO
###

  frontend:
    image: konradkleine/docker-registry-frontend:v2
    ports:
      - "8081:80"
    environment:
      ENV_DOCKER_REGISTRY_HOST: registry
      ENV_DOCKER_REGISTRY_PORT: 5000
    depends_on:
      - registry

###
volumes:
  registry_data: {}
  # registry_data:
  #   driver: nfs
  #   driver_opts:
  #     share: my.nfs.host:/path/to/registry
